---
title: "Parsing domtblout from hmmscan"
author: "Domenico Simone"
date: "September 24, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(data.table)
library(tidyverse)
```

## R Markdown

Parse CDS annotation

```{r}
a <- fread("grep -v '^#' thawponds_assembly.cds.out",
           sep = "\t",
           #skip = "#",
           stringsAsFactors = FALSE,
           select = c(1,4,5,7),
           col.names = c("contigID",
                         "start",
                         "end",
                         "strand")) %>% group_by(contigID) %>% 
                                     mutate(count = sequence(n())) %>%
                                     mutate(CDS_ID = paste(contigID, count, sep = "_")) %>%
                                     subset(select = -count) %>% ungroup()
```

Read hmmscan result table

```{r}
b <- fread("grep -v '^#' thawponds_assembly.cds.split500000.all.hmmer_pfam.domtblout",
           sep = " ",
           stringsAsFactors = FALSE,
           select = c(1,5,18,19),
           col.names = c("CDS_ID",
                         "PFAM_ID",
                         "hit_start",
                         "hit_end"))
```

Conditionally join to hmmscan hits

```{r}
c <- b %>%
  left_join(a) %>%
  mutate(c_start=if_else(strand == "+", start+(hit_start-1)*3, end-hit_end*3)) %>%
  mutate(c_end=if_else(strand == "+", start+hit_end*3, end-(hit_start-1)*3))
```